### ISSUE TITLE
this broke code-server

### ISSUE THREAD

**Issue by Succubussix** [litespeedtech/cyberpanel#102]
I tested it .. 

fresh install server .. i install code server it works fine...

then when i install this i got this

```
WARN  stderr {"data":"(node:26368) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
WARN  stderr {"data":"Error: /tmp/.nbinkkhZL9-spdlog.node: failed to map segment from shared object\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:754:18)\n    at Module.load (internal/modules/cjs/loader.js:611:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:542:3)\n    at Module.require (internal/modules/cjs/loader.js:649:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at bindings (/node_modules/bindings/bindings.js:81:44)\n    at Object.<anonymous> (/node_modules/spdlog/index.js:3:35)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)\n    at Module.load (internal/modules/cjs/loader.js:611:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:542:3)\n    at Module.require (internal/modules/cjs/loader.js:649:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.spdlog (/src/packages/server/build/bootstrap-fork.js.gz:288720:18)\n    at __webpack_require__ (/src/packages/server/build/bootstrap-fork.js.gz:26:30)\n    at Object.createSpdLogService (/src/packages/server/build/bootstrap-fork.js.gz:154372:29)\n    at main (/src/packages/server/build/bootstrap-fork.js.gz:73348:88)\n    at /src/packages/server/build/bootstrap-fork.js.gz:73451:9\n    at Generator.next (<anonymous>)\n    at fulfilled (/src/packages/server/build/bootstrap-fork.js.gz:23310:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n"}
WARN  stderr {"data":"TypeError: _spdlog.setAsyncMode is not a function\n    at Object.createSpdLogService (/src/packages/server/build/bootstrap-fork.js.gz:154373:21)\n    at instantiationService.invokeFunction.accessor (/src/packages/server/build/bootstrap-fork.js.gz:73371:101)\n    at InstantiationService.invokeFunction (/src/packages/server/build/bootstrap-fork.js.gz:150815:27)\n    at main (/src/packages/server/build/bootstrap-fork.js.gz:73367:26)\n    at /src/packages/server/build/bootstrap-fork.js.gz:73451:9\n    at Generator.next (<anonymous>)\n    at fulfilled (/src/packages/server/build/bootstrap-fork.js.gz:23310:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n"}
INFO  Connected to shared process

```

what part of the installations makes it like this ?

**Comment by Succubussix** [comment]
code-server ( without cyber panel ) .. runs everything 
code-server ( with cyberpanel ) runs everything except for terminal because of that error above ..

**Comment by Succubussix** [comment]
rebuilding code-server will work again..
