### ISSUE TITLE
[BUG] cli/cyberPanel.py version is broken

### ISSUE THREAD

**Issue by Lvl4Sword** [litespeedtech/cyberpanel#1168]
**Describe the bug**
When trying to run `cyberpanel version`, the following error occurs:
```py
Traceback (most recent call last):
  File "/usr/bin/cyberpanel", line 1603, in <module>
    main()
  File "/usr/bin/cyberpanel", line 1357, in main
    print(get_cyberpanel_version())
  File "/usr/bin/cyberpanel", line 35, in get_cyberpanel_version
    version = json.loads(str(version_file))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 4)
```

**To Reproduce**
What steps did you take when the issue occurred? 
1. Run `cyberpanel version`
2. See the error

**Expected behavior**
For there to not be an error

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
Version 2.3 / Build: 4 / Current Commit: https://github.com/usmannasir/cyberpanel/commit/c8da443334b8815ec250a0fba606e75355f641cd

**Comment by Lvl4Sword** [comment]
I'll do a commit in a bit, but the fix is
```py
def get_cyberpanel_version():
    with open('/usr/local/CyberCP/version.txt') as version:
        version_file = version.read().split()
    return f"{version_file[0]}.{version_file[1]}"
```

**Comment by usmannasir** [comment]
This seems to be fixed.

**Comment by Lvl4Sword** [comment]
This doesn't appear to be completed

**Comment by Lvl4Sword** [comment]
@usmannasir What made you believe this was completed?

**Comment by usmannasir** [comment]
I can execute `cyberpanel version` on my end, you can not ?

**Comment by master3395** [comment]
Works fine for me also in 2.3.5 - Almalinux 8.9

**Comment by master3395** [comment]
Thanks for the report. This issue is older and may not apply to current releases.

Please confirm:
1) CyberPanel version + build (please retest on the latest public release **2.4.9**)
2) OS name and version (whatever you run, e.g. `cat /etc/os-release`)
3) Exact steps still failing on a current install
4) Relevant logs (no passwords)

Note: the latest public release is **2.4.9**. Development branches are not recommended for reproducing bugs.

If we do not hear back within 30 days, this issue may be closed as stale. You can reopen with fresh details anytime.

**Comment by usmannasir** [comment]
Fixed and released in CyberPanel 3.0.0. Fresh installation now writes `/usr/local/CyberCP/version.txt` as valid JSON matching what the CLI reads, and version parsing no longer depends on fixed offsets.

Commit: https://github.com/usmannasir/cyberpanel/commit/f8ebe295f169444d89d357431583217548e7ac8d

Live validation on the public Ubuntu 26 installation confirms `cyberpanel version` returns `3.0.0`. Closing as completed.
