### ISSUE TITLE
Having troubles with installing on Centos 7[BUG]

### ISSUE THREAD

**Issue by Takanashi-Rikka1** [litespeedtech/cyberpanel#1215]
Hi, i tried to install cyberpanel on my VPS
OS: Centos 7
2vCpu, 4GB RAM, 50GB disk space.

every time i end up with that error:

Traceback (most recent call last):
  File "install.py", line 2599, in <module>
    main()
  File "install.py", line 2480, in main
    mysqlhost, mysqldb, mysqluser, mysqlpassword, mysqlport)
  File "/root/cyberpanel/install/installCyberPanel.py", line 761, in Main
    installer.installLiteSpeed()
  File "/root/cyberpanel/install/installCyberPanel.py", line 103, in installLiteSpeed
    install.preFlightsChecks.call(command, self.distro, command, command, 1, 1, os.EX_OSERR)
  File "/root/cyberpanel/install/install.py", line 233, in call
    res = subprocess.call(shlex.split(command))
  File "/usr/lib64/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dnf': 'dnf'
Oops, something went wrong...

then please it would be great if anyone could help to solve that.

**Comment by usmannasir** [comment]
`https://cyberpanel.net/KnowledgeBase/home/install-cyberpanel/`

Cent7 is not supported anymore.
