### ISSUE TITLE
[BUG] Installation failure on CloudLinux 8.9

### ISSUE THREAD

**Issue by Nemesiz** [litespeedtech/cyberpanel#1219]
**Describe the bug**
Installing CyberPanel on CloudLinux 8.9 installation stop with database configuration

**Error message**

> Traceback (most recent call last):
  File "install.py", line 2599, in <module>
    main()
  File "install.py", line 2480, in main
    mysqlhost, mysqldb, mysqluser, mysqlpassword, mysqlport)
  File "/root/cyberpanel/install/installCyberPanel.py", line 771, in Main
    installer.changeMYSQLRootPassword()
  File "/root/cyberpanel/install/installCyberPanel.py", line 384, in changeMYSQLRootPassword
    install.preFlightsChecks.call(command, self.distro, command, command, 0, 0, os.EX_OSERR)
  File "/root/cyberpanel/install/install.py", line 233, in call
    res = subprocess.call(shlex.split(command))
  File "/usr/lib64/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mysql': 'mysql'
Oops, something went wrong...

**To Reproduce**
1. Run installation script
2. Set to local database
3. Wait until finish

**Additional context**
Full installation process - https://pastebin.com/YM9Ftkx1

**Comment by Nemesiz** [comment]
I had to create /etc/yum.repos.d/MariaDB.repo manually to make installation to work.

Very messy installation script.

**Comment by usmannasir** [comment]
Let me check, sorry was off for few days.

**Comment by usmannasir** [comment]
fixed.
