### ISSUE TITLE
[BUG] Backup Failed

### ISSUE THREAD

**Issue by eakteam** [litespeedtech/cyberpanel#1220]
Just tried to run manual backup (latest version of CP) via `/usr/local/CyberCP/bin/python /usr/local/CyberCP/plogical/IncScheduler.py Weekly`

And it produce this error, tried 3 times, same results but in different timeframe.

```
[02.13.2024_20-23-31] Starting local backup for: xxxxx.com

/usr/local/CyberCP/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[02.13.2024_20-23-33] Waiting for backup to complete..

[02.13.2024_20-24-06] Backup Completed for: xxxxx.com

[02.13.2024_20-24-06] Starting local backup for: xxxxx.com

/usr/local/CyberCP/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[02.13.2024_20-24-08] Waiting for backup to complete..

[02.13.2024_20-25-15] Backup Completed for: xxxxx.com

Traceback (most recent call last):
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'Server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/CyberCP/plogical/IncScheduler.py", line 1592, in <module>
    main()
  File "/usr/local/CyberCP/plogical/IncScheduler.py", line 1583, in main
    IncScheduler.startNormalBackups(args.function)
  File "/usr/local/CyberCP/plogical/IncScheduler.py", line 618, in startNormalBackups
    domain, time.strftime("%m.%d.%Y_%H-%M-%S"))).save()
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/CyberCP/lib/python3.10/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'Server has gone away')
```

**Comment by usmannasir** [comment]
I got your server access from old ticket, just checking.

**Comment by eakteam** [comment]
> I got your server access from old ticket, just checking.

That's hilarious how did you remembered ot 🤯

**Comment by usmannasir** [comment]
Got it from here: https://github.com/usmannasir/cyberpanel/issues/1207

**Comment by eakteam** [comment]
> Got it from here: #1207

I know, but that's still good memory skills 🤣. Usually i don't remember what I did eat before 30 mins, but yes, when programming can remember a bug that happened 5 years before in some of my projects since had bad time solving them, especially at Sundays 🤣🤣🤣

**Comment by usmannasir** [comment]
You have opened many discussions for me to remember your name and tickets :)

I have adjusted some configurations in your my.cnf and this error seems to not come now. 

Looks like not related to CP bug.

thank you. :)

**Comment by eakteam** [comment]
> You have opened many discussions for me to remember your name and tickets :)
> 
> I have adjusted some configurations in your my.cnf and this error seems to not come now.
> 
> Looks like not related to CP bug.
> 
> thank you. :)

Thank you so much for all. May I know what is the root cause of that, just to know what I should debug if it comes again if change again the my.cnf, since my hands never staying without messing around 😊

**Comment by usmannasir** [comment]
Mainly I changed `max_allowed_packet `

**Comment by eakteam** [comment]
@usmannasir Issue still persist, i just tried and it fails.... What i should try next?

**Comment by usmannasir** [comment]
@eakteam I would suggest reaching out to our support so they can tune MySQL, because this is not a CyberPanel bug. I usually work on bug related issues.

They can help you get around it.

hope you understand.
