### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by shelu16** [litespeedtech/cyberpanel#1227]
Traceback (most recent call last):
  File "install.py", line 2599, in <module>
    main()
  File "install.py", line 2479, in main
    installCyberPanel.Main(cwd, mysql, distro, ent, None, port, args.ftp, args.powerdns, args.publicip, remotemysql,
  File "/root/cyberpanel/cyberpanel/install/installCyberPanel.py", line 811, in Main
    installer.fixMariaDB()
  File "/root/cyberpanel/cyberpanel/install/installCyberPanel.py", line 448, in fixMariaDB
    conn = mariadb.connect(user='root', passwd=self.mysql_Root_password)
  File "/usr/local/CyberPanel/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/CyberPanel/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
Oops, something went wrong...

**Comment by usmannasir** [comment]
Please check this guide: https://community.cyberpanel.net/t/some-donts-after-installing-cyberpanel/14195
