### ISSUE TITLE
[BUG] broken cyberpanel

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [litespeedtech/cyberpanel#1280]
**Important**
Do not create a new issue if there is already an issue similar(even if nearly) to yours already posted by someone. Just post an update of your issue in that old issue. At this moment Cyber Panel only have few contributors. Please do not create any maintenance burden.

**Describe the bug**
After upgrade cyber panel cmd completely breaks. 

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

**To Reproduce**
What steps did you take when the issue occurred? 
1. run cyberpanel update
2. it breaks mid update
3. `cyberpanel` cmd breaks

**Expected behavior**
not to throw the error

**Operating system:**
Please enter your answer here (e.g. Ubuntu 20.04 LTS)
`Linux 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
**CyberPanel version:**
Please enter your answer here (e.g. 2.1.1). 
2.3
**Additional context**
Python Error:
```python
Traceback (most recent call last):
  File "/usr/bin/cyberpanel", line 8, in <module>
    django.setup()
  File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/CyberCP/CyberCP/settings.py", line 14, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/usr/local/lib/python3.10/dist-packages/django/utils/translation/__init__.py)
```
Python Version: `Python 3.10.12`

**Comment by shbs9** [comment]
I have tested the update on Ubuntu 20.04, and everything is working well. Could you please provide server access through the platform so I can further investigate if there is anything wrong?
