### ISSUE TITLE
[BUG] 500 erros in all my servers after today's update. Ubuntu 22.04

### ISSUE THREAD

**Issue by Kyro-Cell** [litespeedtech/cyberpanel#1304]
**Describe the bug**
I have three servers. All running Ubuntu 22.04. A few hours ago I updated Cyberpanl. Now the dashboard in all my three servers is inaccessible and throwing 500 error.  

**To Reproduce**
What steps did you take when the issue occurred? 
Updated again.
Reboot the servers multiple times.

**Operating system:**
 (Ubuntu 22.04 LTS)

**CyberPanel version:**
Latest stable which was released a few hours ago.

**Comment by Dimpappas1984** [comment]
Me too in my server. The sites are working but the cyberpanel dashboard just throw 500 error.
![455136956_8030900906985991_8511548796960117734_n](https://github.com/user-attachments/assets/31c2024c-fd85-470f-8e3c-39d3b5d14d48)
I open a ticket also.

**Comment by SaJeTek-Developer** [comment]
Check your `/home/cyberpanel/upgrade_logs` for errors, usually these point you in the right direction and give more context to the errors.

**Comment by kiwimarc** [comment]
For me, it worked by just using this command
`sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)`

**Comment by ghost** [comment]
> For me, it worked by just using this command `sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)`

For me, it did not help.
preUpgrade results in an pip cloudflare error.
```
Collecting cloudflare==2.8.13 (from -r /usr/local/requirments.txt (line 5))
  Using cached cloudflare-2.8.13.tar.gz (65 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info
      writing /tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info/entry_points.txt
      writing requirements to /tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-659cu9_l/cloudflare.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-98zr7uwv/cloudflare_a9368bed35c441ca856bb09dfa544b70/setup.py", line 60, in <module>
          main()
        File "/tmp/pip-install-98zr7uwv/cloudflare_a9368bed35c441ca856bb09dfa544b70/setup.py", line 18, in main
          setup(
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/dist.py", line 991, in run_command
          super().run_command(command)
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 315, in run
          self.find_sources()
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 323, in find_sources
          mm.run()
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.prune_file_list()
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/command/sdist.py", line 161, in prune_file_list
          super().prune_file_list()
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/usr/local/CyberPanel/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
```

**Comment by gediminaskv** [comment]
I got these warnings while upgrading on CentOS 7:

> [11.14.2024_16-41-45] CLI Symlink failed.
> [11.14.2024_16-43-00] fix csf if there failed.
> [11.14.2024_16-45-51] chmod +x /usr/local/CyberCP/public/imunifyav/bin/execute.py failed.

Websites are running except CyberPanel. 503 error is thrown.

LSCP error log:

> 2024-11-23 19:37:55.009987 [INFO] checkStatusFile() called with uid 5001 randoffset -1.
2024-11-23 19:37:55.010087 [INFO] checkStatusFile() return 1.
2024-11-23 19:38:43.827838 [INFO] [wsgi:cyberpanel:/] add child process pid: 727708.
2024-11-23 19:38:44.028459 [INFO] Process with PID: 727708 is dead 
2024-11-23 19:38:46.035048 [NOTICE] [ip:36268] ExtConn timed out while processing.
2024-11-23 19:38:46.035880 [INFO] [wsgi:cyberpanel:/] add child process pid: 727709.
2024-11-23 19:38:47.038267 [INFO] Process with PID: 727709 is dead 
2024-11-23 19:38:49.046714 [NOTICE] [ip:36268] ExtConn timed out while processing.
2024-11-23 19:38:49.047961 [INFO] [wsgi:cyberpanel:/] add child process pid: 727722.
2024-11-23 19:38:50.050135 [INFO] Process with PID: 727722 is dead 
2024-11-23 19:38:52.057493 [NOTICE] [ip:36268] ExtConn timed out while processing.
2024-11-23 19:38:52.725407 [INFO] [wsgi:cyberpanel:/] add child process pid: 727723.
2024-11-23 19:38:53.026382 [INFO] Process with PID: 727723 is dead 
2024-11-23 19:38:55.030631 [NOTICE] [ip:36274] ExtConn timed out while processing.
2024-11-23 19:38:55.031429 [INFO] [wsgi:cyberpanel:/] add child process pid: 727724.
2024-11-23 19:38:55.034449 [INFO] checkStatusFile() called with uid 5001 randoffset -1.
2024-11-23 19:38:55.034735 [INFO] checkStatusFile() return 1.
2024-11-23 19:38:56.037437 [INFO] Process with PID: 727724 is dead 
2024-11-23 19:38:58.045659 [NOTICE] [ip:36274] ExtConn timed out while processing.
2024-11-23 19:38:58.046327 [INFO] [wsgi:cyberpanel:/] add child process pid: 727725.
2024-11-23 19:38:59.050144 [INFO] Process with PID: 727725 is dead 
2024-11-23 19:39:01.061159 [NOTICE] [ip:36274] ExtConn timed out while processing.

**Comment by Alex9001** [comment]
Same thing Alma 9

**Comment by tcope25** [comment]
I have tried to upgrade in Cent OS 7 and receive the 503 Error. Logs state: ExtConn timed out while processing. No idea how to proceed.

**Comment by master3395** [comment]
Thanks for the report. This issue is older and may not apply to current releases.

Please confirm:
1) CyberPanel version + build (please retest on the latest public release **2.4.9**)
2) OS name and version (whatever you run, e.g. `cat /etc/os-release`)
3) Exact steps still failing on a current install
4) Relevant logs (no passwords)

Note: the latest public release is **2.4.9**. Development branches are not recommended for reproducing bugs.

If we do not hear back within 30 days, this issue may be closed as stale. You can reopen with fresh details anytime.
