### ISSUE TITLE
[BUG] UnicodeEncodeError: 'utf-8'

### ISSUE THREAD

**Issue by thanhtuyen2024** [litespeedtech/cyberpanel#1310]
i got error while installing cyberpanel on ubuntu 20.04
```
Traceback (most recent call last):
  File "install.py", line 2628, in <module>
    main()
  File "install.py", line 2472, in main
    print('mysqlhost: %s, mysqldb: %s,  mysqluser: %s, mysqlpassword: %s, mysqlport: %s' % (
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 55: surrogates not allowed
Oops, something went wrong...
```

**Comment by usmannasir** [comment]
Closing this as no context is provided to the problem.
