### ISSUE TITLE
Exception: Warning: SessionHandler::read(): open(/var/lib/lsphp/session/sess_b6b46e57756495mcjbee1mdepu, O_RDWR) failed: Permission denied (

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#442]
Problem:
```bash
Exception: Warning: SessionHandler::read(): open(/var/lib/lsphp/session/sess_b6b46e57756495mcjbee1mdepu, O_RDWR) failed: Permission denied (13) in /home/example.com/public_html/vendor/magento/framework/Session/SaveHandler/Native.php on line 22 in /home/example.com/public_html/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'SessionHandler:...', '/home/example.c...', 22, Array) #1 /home/example.com/public_html/vendor/magento/framework/Session/SaveHandler/Native.php(22): SessionHandler->read('b6b46e57756495m...') #2 /home/example.com/public_html/vendor/magento/framework/Session/SaveHandler.php(138): Magento\Framework\Session\SaveHandler\Native->read('b6b46e57756495m...') #3 /home/example.com/public_html/vendor/magento/framework/Session/SaveHandler.php(83): Magento\Framework\Session\SaveHandler->callSafely('read', 'b6b46e57756495m...') #4 [internal function]: Magento\Framework\Session\SaveHandler->read('b6b46e57756495m...') #5 /home/example.com/public_html/vendor/magento/framework/Session/SessionManager.php(204): session_start() #6 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Session\SessionManager->start() #7 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Session\Generic\Interceptor->___callParent('start', Array) #8 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Session\Generic\Interceptor->Magento\Framework\Interception\{closure}() #9 /home/example.com/public_html/generated/code/Magento/Framework/Session/Generic/Interceptor.php(52): Magento\Framework\Session\Generic\Interceptor->___callPlugins('start', Array, Array) #10 /home/example.com/public_html/vendor/magento/framework/Session/SessionManager.php(141): Magento\Framework\Session\Generic\Interceptor->start() #11 /home/example.com/public_html/generated/code/Magento/Framework/Session/Generic/Interceptor.php(14): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor), NULL) #12 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Session\Generic\Interceptor->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor), NULL) #13 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) #14 /home/example.com/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #15 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #16 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'session', 'Magento\\Custome...') #17 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Custome...', Array, Array) #18 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Custome...', Array, Array) #19 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Custome...', Array, Array) #20 /home/example.com/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Custome...') #21 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Custome...') #22 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Custome...', NULL, 'customerSession', 'Magento\\Checkou...') #23 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Checkou...', Array, Array) #24 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Checkou...', Array, Array) #25 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Checkou...', Array, Array) #26 /home/example.com/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Checkou...') #27 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Checkou...') #28 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Checkou...', NULL, 'checkoutSession', 'Magento\\Persist...') #29 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Persist...', Array, Array) #30 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Persist...', Array, Array) #31 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Persist...', Array, Array) #32 /home/example.com/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Persist...') #33 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Persist...') #34 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Persist...', NULL, 'persistentSessi...', 'Magento\\Persist...') #35 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Persist...', Array, Array) #36 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Persist...', Array, Array) #37 /home/example.com/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Persist...', Array, Array) #38 /home/example.com/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Persist...') #39 /home/example.com/public_html/vendor/magento/framework/Interception/PluginList/PluginList.php(250): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Persist...') #40 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(119): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Framewo...', 'persistent_page...') #41 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Context\Interceptor->Magento\Framework\Interception\{closure}() #42 /home/example.com/public_html/generated/code/Magento/Framework/App/Http/Context/Interceptor.php(78): Magento\Framework\App\Http\Context\Interceptor->___callPlugins('getVaryString', Array, Array) #43 /home/example.com/public_html/vendor/magento/framework/App/Response/Http.php(108): Magento\Framework\App\Http\Context\Interceptor->getVaryString() #44 /home/example.com/public_html/generated/code/Magento/Framework/App/Response/Http/Interceptor.php(37): Magento\Framework\App\Response\Http->sendVary() #45 /home/example.com/public_html/vendor/magento/module-page-cache/Model/App/Response/HttpPlugin.php(25): Magento\Framework\App\Response\Http\Interceptor->sendVary() #46 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\PageCache\Model\App\Response\HttpPlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor)) #47 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}() #48 /home/example.com/public_html/generated/code/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array) #49 /home/example.com/public_html/vendor/magento/framework/App/ExceptionHandler.php(103): Magento\Framework\App\Response\Http\Interceptor->sendResponse() #50 /home/example.com/public_html/vendor/magento/framework/App/ExceptionHandler.php(70): Magento\Framework\App\ExceptionHandler->handleDeveloperMode(Object(Magento\Framework\App\Bootstrap), Object(Exception), Object(Magento\Framework\App\Response\Http\Interceptor)) #51 /home/example.com/public_html/vendor/magento/framework/App/Http.php(156): Magento\Framework\App\ExceptionHandler->handle(Object(Magento\Framework\App\Bootstrap), Object(Exception), Object(Magento\Framework\App\Response\Http\Interceptor), Object(Magento\Framework\App\Request\Http)) #52 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception)) #53 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('catchException', Array) #54 /home/example.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Bootstrap), Object(Exception)) #55 /home/example.com/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(39): Magento\Framework\App\Http\Interceptor->___callPlugins('catchException', Array, Array) #56 /home/example.com/public_html/vendor/magento/framework/App/Bootstrap.php(267): Magento\Framework\App\Http\Interceptor->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception)) #57 /home/example.com/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #58 {main}
```

note: changed the original domain to example.com

**Steps:**

1. Install fresh cyberpanel with centos 7
2. Download magento 2.3.5-p2 with sample data
3. Extract magento and follow the installation steps
4. After installation finish, try to open the site or admin 

The session directory permission:
```bash
ls -l /var/lib/lsphp/
total 8
drwx-wx-wt. 2 root root 4096 Sep 22 09:51 session
```

The **NOT RECOMMENDED** workaround:
```bash
chmod 777 /var/lib/lsphp/session/
```

**NOTE:** Please, users from google, do not use this workaround.

**Comment by qtwrk** [comment]
could you please try this command , and see if it helps ?

`bash <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/CPScripts/setup_php_sessions.sh)`

**Comment by franciscopaniskaseker** [comment]
@qtwrk seems fixed. I returned all original permissions and applied your script. And worked.

**Comment by meramsey** [comment]
thanks for the confirmation. closing this now as this is fixed by the above mentioned script
