### ISSUE TITLE
Docker installation on 20.04 or 18.04 problem

### ISSUE THREAD

**Issue by gitmko0** [litespeedtech/cyberpanel#477]
problem as below. possible to make it docker compatible?
what is the exact problem?

Setting up iproute2 (4.15.0-2ubuntu1.2) ...
Setting up libcgi-fast-perl (1:2.13-1) ...
Setting up libdbd-mysql-perl (4.046-1) ...
Setting up mariadb-client-10.1 (1:10.1.47-0ubuntu0.18.04.1) ...
Setting up mariadb-server-10.1 (1:10.1.47-0ubuntu0.18.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up mariadb-server (1:10.1.47-0ubuntu0.18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...

[11.04.2020_21-44-33] #########################################################################

[11.04.2020_21-44-33] Successfully ran: apt-get -y install mariadb-server.

[11.04.2020_21-44-33] #########################################################################

[11.04.2020_21-44-33] #########################################################################

[11.04.2020_21-44-33] Running: systemctl start mariadb

[11.04.2020_21-44-33] #########################################################################

Traceback (most recent call last):
  File "install.py", line 2389, in <module>
    main()
  File "install.py", line 2273, in main
    installCyberPanel.Main(cwd, mysql, distro, ent, None, port, args.ftp, args.powerdns, args.publicip, remotemysql, mysqlhost, mysqldb, mysqluser, mysqlpassword, mysqlport)
  File "/cyberpanel/install/installCyberPanel.py", line 663, in Main
    installer.installMySQL(mysql)
  File "/cyberpanel/install/installCyberPanel.py", line 267, in installMySQL
    self.startMariaDB()
  File "/cyberpanel/install/installCyberPanel.py", line 290, in startMariaDB
    install.preFlightsChecks.call(command, self.distro, command, command, 1, 1, os.EX_OSERR)
  File "/cyberpanel/install/install.py", line 217, in call
    res = subprocess.call(shlex.split(command))
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl': 'systemctl'
Oops, something went wrong...

**Comment by usmannasir** [comment]
Hello

CyberPanel is kind of application which is not suitable to run in docker environment.
