### ISSUE TITLE
PLEASE HELP ME! I am stuck since few days and I have very critical dependencies

### ISSUE THREAD

**Issue by KewalT** [litespeedtech/cyberpanel#709]
Platform: Oracle cloud, Mumbai server
OS: Ubuntu 20
Fresh Installation.

Now I just tried again on new instance. On fresh instance I ran these commands first : 

wget -O acme.sh https://get.acme.sh
chmod +x acme.sh
./acme.sh6. After installing acme.sh rerun the installation script - 
sh <(curl https://cyberpanel.net/install.sh || wget -O - https://cyberpanel.net/install.sh)

Then our main command - sh <(curl https://cyberpanel.net/install.sh || wget -O - https://cyberpanel.net/install.sh)

Still got below error:

[08.14.2021_04-52-16] #########################################################################

[08.14.2021_04-52-16] Running: apt-get -y install cron

[08.14.2021_04-52-16] #########################################################################

Reading package lists... Done
Building dependency tree
Reading state information... Done
cron is already the newest version (3.0pl1-136ubuntu1).
cron set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

[08.14.2021_04-52-17] #########################################################################

[08.14.2021_04-52-17] Successfully ran: apt-get -y install cron.

[08.14.2021_04-52-17] #########################################################################

[08.14.2021_04-52-17] #########################################################################

[08.14.2021_04-52-17] Running: systemctl enable cron

[08.14.2021_04-52-17] #########################################################################

Synchronizing state of cron.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable cron

[08.14.2021_04-52-20] #########################################################################

[08.14.2021_04-52-20] Successfully ran: systemctl enable cron.

[08.14.2021_04-52-20] #########################################################################

[08.14.2021_04-52-20] #########################################################################

[08.14.2021_04-52-20] Running: systemctl start cron

[08.14.2021_04-52-20] #########################################################################

[08.14.2021_04-52-20] #########################################################################

[08.14.2021_04-52-20] Successfully ran: systemctl start cron.

[08.14.2021_04-52-20] #########################################################################

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-21] Running: chmod 600 /var/spool/cron/crontabs/root

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-21] Successfully ran: chmod 600 /var/spool/cron/crontabs/root.

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-21] Running: systemctl restart cron.service

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-21] Successfully ran: systemctl restart cron.service.

[08.14.2021_04-52-21] #########################################################################

[08.14.2021_04-52-22] #########################################################################

[08.14.2021_04-52-22] Running: apt-get update -y

[08.14.2021_04-52-22] #########################################################################

Ign:1 http://rpms.litespeedtech.com/debian focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://rpms.litespeedtech.com/debian focal Release
Hit:5 http://ap-mumbai-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal InRelease
Hit:6 http://ap-mumbai-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:7 http://ap-mumbai-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done

[08.14.2021_04-52-28] #########################################################################

[08.14.2021_04-52-28] Successfully ran: apt-get update -y.

[08.14.2021_04-52-28] #########################################################################

[08.14.2021_04-52-28] #########################################################################

[08.14.2021_04-52-28] Running: apt-get install restic -y

[08.14.2021_04-52-28] #########################################################################

Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  libjs-jquery libjs-underscore
The following NEW packages will be installed:
  restic
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 8,524 kB of archives.
After this operation, 25.7 MB of additional disk space will be used.
Get:1 http://ap-mumbai-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal/universe amd64 restic amd64 0.9.6+ds-2 [8,524 kB]
Fetched 8,524 kB in 4s (2,135 kB/s)
Selecting previously unselected package restic.
(Reading database ... 87533 files and directories currently installed.)
Preparing to unpack .../restic_0.9.6+ds-2_amd64.deb ...
Unpacking restic (0.9.6+ds-2) ...
Setting up restic (0.9.6+ds-2) ...
Processing triggers for man-db (2.9.1-1) ...

[08.14.2021_04-52-42] #########################################################################

[08.14.2021_04-52-42] Successfully ran: apt-get install restic -y.

[08.14.2021_04-52-42] #########################################################################

--2021-08-14 04:52:43--  https://get.acme.sh/
Resolving get.acme.sh (get.acme.sh)... 172.67.199.16, 104.21.34.62, 2606:4700:3032::6815:223e, ...
Connecting to get.acme.sh (get.acme.sh)|172.67.199.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

-                                                   [<=>                                                                                                  ]       0  --.-KB/s               sh: 1: Syntax error: redirection unexpected
-                                                   [ <=>                                                                                                 ]     360  --.-KB/s    in 0s

2021-08-14 04:52:43 (23.4 MB/s) - written to stdout [360]

[08.14.2021_04-52-43] #########################################################################

[08.14.2021_04-52-43] Running: /root/.acme.sh/acme.sh --upgrade --auto-upgrade

[08.14.2021_04-52-43] #########################################################################

Traceback (most recent call last):
  File "install.py", line 2357, in <module>
    main()
  File "install.py", line 2271, in main
    checks.installAcme()
  File "install.py", line 2089, in installAcme
    preFlightsChecks.call(command, self.distro, command, command, 1, 0, os.EX_OSERR)
  File "install.py", line 219, in call
    res = subprocess.call(shlex.split(command))
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.acme.sh/acme.sh'
Oops, something went wrong...
root@o

_Originally posted by @KewalT in https://github.com/usmannasir/cyberpanel/issues/707#issuecomment-898820873_

**Comment by istiak101** [comment]
Please do not open any new issues for acme.sh. A workaround was already provided for that. Keep this in one issue.

**Comment by KewalT** [comment]
As mentioned earlier the work around provided didn't solve the issue. I already followed those steps and still the issue persisted.

This is not related to previous or existing of any tickets hence created a new ticket.

Here I am insisting on the solution, so kindly keep the new ticket open till this issue is resolved. I am definitely open to all the suggestions to solve the issue.

**Comment by KewalT** [comment]
Kindly reopen till this is resolved
