### ISSUE TITLE
New installtion getting broken  ssl certificate script link not working 

### ISSUE THREAD

**Issue by l33tx0** [litespeedtech/cyberpanel#713]
**broken link : https://get.acme.sh/**

`Installed:
  restic.x86_64 0:0.12.0-1.el7

Complete!

[08.20.2021_21-51-07] #########################################################################

[08.20.2021_21-51-07] Successfully ran: yum install -y restic.

[08.20.2021_21-51-07] #########################################################################

--2021-08-20 21:51:07--  https://get.acme.sh/
Resolving get.acme.sh (get.acme.sh)... 172.67.199.16, 104.21.34.62, 2606:4700:3032::6815:223e, ...
Connecting to get.acme.sh (get.acme.sh)|172.67.199.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

    [ <=>                                                                                                                                          ] 360         --.-K/s   in 0s

2021-08-20 21:51:07 (30.6 MB/s) - written to stdout [360]

sh: line 1: syntax error near unexpected token `<'
sh: line 1: `<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="https://182.79.218.34:8080/webadmin/deny/index.php?dpid=15&dpruleid=11&cat=107&dplanguage=-&url=http%3a%2f%2f185%2e199%2e111%2e153%2f" width="100%" height="100%" frameborder=0></iframe>'

[08.20.2021_21-51-07] #########################################################################

[08.20.2021_21-51-07] Running: /root/.acme.sh/acme.sh --upgrade --auto-upgrade

[08.20.2021_21-51-07] #########################################################################

Traceback (most recent call last):
  File "install.py", line 2357, in <module>
    main()
  File "install.py", line 2271, in main
    checks.installAcme()
  File "install.py", line 2089, in installAcme
    preFlightsChecks.call(command, self.distro, command, command, 1, 0, os.EX_OSERR)
  File "install.py", line 219, in call
    res = subprocess.call(shlex.split(command))
  File "/usr/lib64/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.acme.sh/acme.sh': '/root/.acme.sh/acme.sh'
Oops, something went wrong...`

**Comment by qtwrk** [comment]
updated in https://github.com/usmannasir/cyberpanel/commit/e40117ce43cbef3c6cf72fcbe45aa990fc6b25cc
